version: '3.0'

services:
  cats-api:
    image: postgres:12
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cats-api